const locations = {
  sandbox: {
    name: "sandbox",
    paths: ["sandbox", "sandbox"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["sandbox", "sandbox"],
    transition: { type: "pixelate-no-blur", time: 1000 },
    html: {},
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
  },
  intro: {
    name: "intro",
    paths: ["forestNorth", "forestSouth"],
    choicePrompts: {
      mobile: "How should they leave?",
      display: "How should they leave?",
    },
    choices: ["north", "south"],
    html: {},
    transition: { type: "pixelate-no-blur", time: 1000 },
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
  },
  kingdom: {
    name: "kingdom",
    paths: ["forestNorth", "forestSouth"],
    choicePrompts: {
      mobile: "How should they leave?",
      display: "How should they leave?",
    },
    choices: ["north", "south"],
    html: {},
    transition: { type: "jump", time: 0 },
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
  },
  forestNorth: {
    name: "forestNorth",
    paths: ["cave", "river"],
    choicePrompts: {
      mobile: "Which way should they go?",
      display: "Which way should we go?",
    },
    choices: ["left", "right"],
    html: {},
    voteBg: "/display/assets/backgrounds/ForestTest.jpg",
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
    transition: { type: "pixelate", time: 1000 },
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
  },
  forestSouth: {
    name: "forestSouth",
    paths: ["river", "cave"],
    choicePrompts: {
      mobile: "Which way should they go?",
      display: "Which way should we go?",
    },
    choices: ["Left", "Right"],
    html: {},
    transition: { type: "blur", time: 1000 },
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
  },
  cave: {
    name: "cave",
    paths: ["bats", "bugs"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Left", "Right"],
    html: {},
    transition: { type: "blur", time: 1000 },
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
  },
  river: {
    name: "river",
    paths: ["bugs", "fish"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Left", "Right"],
    html: {},
    transition: { type: "pull", time: 2000 },
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
  },
  bats: {
    name: "bats",
    paths: ["chatBats", "fightBats"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Chat", "Fight"],
    html: {},
    movingSprites: true,
    transition: { type: "blur", time: 1000 },
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
  },
  batMadlib: {
    name: "batMadlib",
    paths: ["chatBats", "fightBats"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Chat", "Fight"],
    html: {},
    movingSprites: true,
    transition: { type: "fade", time: 1000 },
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
  },
  bugs: {
    name: "bugs",
    paths: ["chatBugs", "fightBugs"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Chat", "Fight"],
    html: {},
    transition: { type: "pull", time: 2000 },
    voteBgBlur: "/display/assets/backgrounds/forestBLur.png",
  },
  fish: {
    name: "fish",
    paths: ["chatFish", "fightFish"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Chat", "Fight"],
    html: {},
    transition: { type: "fade", time: 1000 },
  },
  chatFish: {
    name: "chatFish",
    paths: ["pacifist", "pacifist"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Left", "Right"],
    html: {},
    transition: { type: "fade", time: 1000 },
  },
  fightFish: {
    name: "fightFish",
    paths: ["spaceBuff", "oceanBuff"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Space Weapon", "Ocean Weapon"],
    html: {},
    transition: { type: "fade", time: 1000 },
  },
  chatBats: {
    name: "chatBats",
    paths: ["pacifist", "pacifist"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Left", "Right"],
    html: {},
    transition: { type: "fade", time: 1000 },
  },
  fightBats: {
    name: "fightBats",
    paths: ["spaceBuff", "oceanBuff"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Space Weapon", "Ocean Weapon"],
    html: {},
    transition: { type: "fade", time: 1000 },
  },
  chatBugs: {
    name: "chatBugs",
    paths: ["pacifist", "pacifist"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Left", "Right"],
    html: {},
    transition: { type: "fade", time: 1000 },
  },
  fightBugs: {
    name: "fightBugs",
    paths: ["spaceBuff", "oceanBuff"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Space Weapon", "Ocean Weapon"],
    html: {},
    transition: { type: "fade", time: 1000 },
  },
  spaceBuff: {
    name: "spaceBuff",
    paths: ["fightSpace", "explainSpace"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Fight", "Explain yourself"],
    html: {},
    transition: { type: "fade", time: 3000 },
  },
  oceanBuff: {
    name: "oceanBuff",
    paths: ["fightOcean", "explainOcean"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: ["Fight", "Explain yourself"],
    html: {},
  },
  pacifist: {
    name: "pacifist",
    paths: ["thermosphere", "mesopelagic"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: [
      "To the THERMOSPHERE, amidst the Aurora Borealis.",
      "To the MESOPELAGIC ZONE, the ocean's twilight zone.",
    ],
    html: {},
    transition: { type: "fade", time: 3000 },
  },
  fightSpace: {
    name: "fightSpace",
    paths: ["thermosphere", "mesopelagic"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: [
      "To the THERMOSPHERE, amidst the Aurora Borealis.",
      "To the MESOPELAGIC ZONE, the ocean's twilight zone.",
    ],
    html: {},
    transition: { type: "fade", time: 3000 },
  },
  explainSpace: {
    name: "explainSpace",
    paths: ["thermosphere", "mesopelagic"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: [
      "To the THERMOSPHERE, amidst the Aurora Borealis.",
      "To the MESOPELAGIC ZONE, the ocean's twilight zone.",
    ],
    html: {},
    transition: { type: "fade", time: 3000 },
  },
  fightOcean: {
    name: "fightOcean",
    paths: ["thermosphere", "mesopelagic"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: [
      "To the THERMOSPHERE, amidst the Aurora Borealis.",
      "To the MESOPELAGIC ZONE, the ocean's twilight zone.",
    ],
    html: {},
    transition: { type: "fade", time: 3000 },
  },
  explainOcean: {
    name: "explainOcean",
    paths: ["thermosphere", "mesopelagic"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: [
      "To the THERMOSPHERE, amidst the Aurora Borealis.",
      "To the MESOPELAGIC ZONE, the ocean's twilight zone.",
    ],
    html: {},
    transition: { type: "fade", time: 3000 },
  },
  thermosphere: {
    name: "thermosphere",
    paths: ["thermosphere", "mesopelagic"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: [
      "To the THERMOSPHERE, amidst the Aurora Borealis.",
      "To the MESOPELAGIC ZONE, the ocean's twilight zone.",
    ],
    html: {},
    transition: { type: "fade", time: 3000 },
  },
  mesopelagic: {
    name: "mesopelagic",
    paths: ["thermosphere", "mesopelagic"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: [
      "To the THERMOSPHERE, amidst the Aurora Borealis.",
      "To the MESOPELAGIC ZONE, the ocean's twilight zone.",
    ],
    html: {},
    transition: { type: "fade", time: 3000 },
  },
  sampletest: {
    name: "sampletest",
    paths: ["thermosphere", "mesopelagic"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: [
      "To the THERMOSPHERE, amidst the Aurora Borealis.",
      "To the MESOPELAGIC ZONE, the ocean's twilight zone.",
    ],
    html: {},
    transition: { type: "fade", time: 3000 },
  },
  welcome: {
    name: "welcome",
    paths: ["thermosphere", "mesopelagic"],
    choicePrompts: {
      mobile: "",
      display: "",
    },
    choices: [
      "To the THERMOSPHERE, amidst the Aurora Borealis.",
      "To the MESOPELAGIC ZONE, the ocean's twilight zone.",
    ],
    html: {},
    transition: { type: "fade", time: 3000 },
  },
};

module.exports = locations;
