function fight() {
    renderPino()
    renderJaz()
    toggleAnimation("side", "duo")
    changeNPCSrc(`${history.locationsVisited[history.locationsVisited.length - 2].name.slice(0, -1)}/full.png`)
    jumpChar("npc", 550, 0)
    changeSize("npc", 1, .7)
    jumpChar("duo", 0, 50)
    changeSize("duo", 1, .8)
    setTimeout(throwHats, 1000)
    // throwHats()
    // robeAura()
    // deviceDrop()
    // noisyBonk()
    // collarRoll()
    // hatSpike()
    // duoAttack()
}

fight()
