let btnEl1 = document.querySelector(".sample-btn1")
btnEl1.addEventListener("click", () => { sendToServer({ type: "sample", val: "drum 1" }) })
let btnEl2 = document.querySelector(".sample-btn2")
btnEl2.addEventListener("click", () => { sendToServer({ type: "sample", val: "drum 2" }) })
let btnEl3 = document.querySelector(".sample-btn3")
btnEl3.addEventListener("click", () => { sendToServer({ type: "sample", val: "drum 3" }) })
let btnEl4 = document.querySelector(".sample-btn4")
btnEl4.addEventListener("click", () => { sendToServer({ type: "sample", val: "synth 1" }) })